name: Build app and deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@v1
      # 安装Node13
      - name: use Node.js 15
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 15
      # 安装依赖
      - name: install and build
        run: |
        npm install yarn -g
        yarn
        yarn build
      # # 打包
      # - name: npm build
      #   run: yarn build
      # 部署到阿里云
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: "./dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: "root"
          # 目标地址
          TARGET: "/data/fushu/recovery/platform-test-wx/"
